pipeline:
  name: Build and Push NGINX
  identifier: Build_adithya10_12ramesh_Harness_io_1751003503138
  projectIdentifier: Harnessio
  orgIdentifier: default
  tags: {}
  variables:
    - name: AWS_REGION
      type: String
      value: ap-south-1
    - name: ECR_REPO_URI
      type: String
      value: <+secrets.getValue("ecr_repo_uri")>
  stages:
    - stage:
        name: Push NGINX to ECR
        identifier: push_nginx
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Create Dockerfile for NGINX
                  identifier: create_dockerfile
                  spec:
                    shell: Sh
                    command: |
                      echo 'FROM nginx:latest' > Dockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push to ECR
                  identifier: build_push_nginx
                  spec:
                    connectorRef: docker-delegate
                    repo: <+pipeline.variables.ECR_REPO_URI>
                    tags:
                      - latest
                    dockerfile: Dockerfile
                    context: .
                    optimize: true
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: 1000m
          delegateSelectors:
            - docker3-delegate
        delegateSelectors:
          - docker3-delegate
