pipeline:
  name: Build and Push NGINX from Git Repo
  identifier: Build_adithya10_12ramesh_Harness_io_1751003503138
  projectIdentifier: Harnessio
  orgIdentifier: default
  tags: {}
  variables:
    - name: AWS_REGION
      type: String
      value: ap-south-1
    - name: ECR_REPO_URI
      type: String
      value: 680871073643.dkr.ecr.ap-south-1.amazonaws.com/nginx
  properties:
    ci:
      codebase:
        connectorRef: GitHub
        repoName: harness
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: Clone and Push NGINX to ECR
        identifier: push_nginx
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Show repo contents
                  identifier: show_repo
                  spec:
                    shell: Sh
                    command: |
                      echo "=== working dir ==="
                      pwd
                      echo "=== files ==="
                      ls -la
                      echo "=== Dockerfile ==="
                      [ -f Dockerfile ] && cat Dockerfile || echo "Dockerfile NOT FOUND"
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: YOUR_AWS_CONNECTOR_ID
                    region: ap-south-1
                    account: "680871073643"
                    imageName: nginx
                    tags:
                      - latest
          delegateSelectors:
            - docker5-delegate
