pipeline:
  name: Build and Push NGINX from Git Repo
  identifier: Build_adithya10_12ramesh_Harness_io_1751003503138
  projectIdentifier: Harnessio
  orgIdentifier: default
  tags: {}
  variables:
    - name: AWS_REGION
      type: String
      value: ap-south-1
    - name: ECR_REPO_URI
      type: String
      value: <+secrets.getValue("ecr_repo_uri")>
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_Github
        repoName: adithya10-12ramesh/Harness.io-nginx
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: Clone and Push NGINX to ECR
        identifier: push_nginx
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push to ECR
                  identifier: build_push_nginx
                  spec:
                    connectorRef: docker_ecr_reg
                    repo: <+pipeline.variables.ECR_REPO_URI>
                    tags:
                      - latest
                    dockerfile: Dockerfile
                    context: .
                    optimize: true
                    resources:
                      limits:
                        memory: 2Gi
                        cpu: 1000m
          delegateSelectors:
            - docker5-delegate
