pipeline:
  name: Build_and_Push_NGINX
  identifier: Build_adithya10_12ramesh_Harness_io_1751003503138
  projectIdentifier: Harnessio
  orgIdentifier: default
  tags: {}
  variables:
    - name: AWS_REGION
      type: String
      value: ap-south-1
    - name: ECR_REPO_URI
      type: String
      value: <+secrets.getValue("ecr_repo_uri")>
  stages:
    - stage:
        name: Build and Push
        identifier: Build_and_Push
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Pull and Tag NGINX
                  identifier: pull_tag_nginx
                  spec:
                    shell: Sh
                    command: |
                      docker pull nginx:latest
                      docker tag nginx:latest <+pipeline.variables.ECR_REPO_URI>:latest
              - step:
                  type: Run
                  name: Login to ECR
                  identifier: login_to_ecr
                  spec:
                    shell: Sh
                    command: |
                      aws ecr get-login-password --region <+pipeline.variables.AWS_REGION> \
                      | docker login --username AWS --password-stdin <+pipeline.variables.ECR_REPO_URI>
              - step:
                  type: Run
                  name: Push to ECR
                  identifier: push_to_ecr
                  spec:
                    shell: Sh
                    command: |
                      docker push <+pipeline.variables.ECR_REPO_URI>:latest
          delegateSelectors:
            - docker-delegate
