pipeline:
  name: Build and Push NGINX from Git Repo
  identifier: Build_adithya10_12ramesh_Harness_io_1751003503138
  projectIdentifier: Harnessio
  orgIdentifier: default
  tags: {}
  variables:
    - name: AWS_REGION
      type: String
      value: ap-south-1
    - name: ECR_REPO_URI
      type: String
      value: 680871073643.dkr.ecr.ap-south-1.amazonaws.com/nginx
  properties:
    ci:
      codebase:
        connectorRef: GitHub
        repoName: harness
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: Clone and Push NGINX to ECR
        identifier: push_nginx
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Show repo contents
                  identifier: show_repo
                  spec:
                    shell: Sh
                    command: |
                      echo "=== working dir ==="
                      pwd
                      echo "=== files ==="
                      ls -la
                      echo "=== Dockerfile ==="
                      [ -f Dockerfile ] && cat Dockerfile || echo "Dockerfile NOT FOUND"
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: aws_connector
                    region: ap-south-1
                    account: "680871073643"
                    imageName: nginx
                    tags:
                      - latest
          delegateSelectors:
            - docker5-delegate
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: Deploy NGINX to EC2
        identifier: deploy_nginx_ec2
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: Deploy Container from ECR
                  identifier: deploy_container
                  type: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    image: amazon/aws-cli:2.15.28
                    source:
                      type: Inline
                      spec:
                        script: |
                          AWS_REGION="ap-south-1"
                          ECR_REPO="680871073643.dkr.ecr.ap-south-1.amazonaws.com/nginx"

                          echo "🔧 Installing Docker..."
                           apt update -y
                           apt install -y docker.io
                           systemctl start docker
                           systemctl enable docker

                          echo "🔐 Logging into ECR..."
                          aws ecr get-login-password --region "$AWS_REGION" \
                            |  docker login --username AWS --password-stdin "$ECR_REPO"

                          echo "📦 Pulling image from ECR..."
                           docker pull "$ECR_REPO:latest"

                          echo "🧹 Cleaning old container..."
                           docker stop nginx || true
                           docker rm nginx || true

                          echo "🚀 Running NGINX container..."
                           docker run -d --name nginx -p 80:80 "$ECR_REPO:latest"
              - step:
                  name: Health Check
                  identifier: health_check
                  type: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "🩺 Checking if NGINX is up..."
                          sleep 5
                          curl --fail http://localhost || exit 1
          environment:
            environmentRef: production_env
            deployToAll: false
            infrastructureDefinitions:
              - identifier: ssh_infra
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - docker5-delegate
