pipeline:
  name: Build and Push NGINX from Git Repo
  identifier: Build_adithya10_12ramesh_Harness_io_1751003503138
  projectIdentifier: Harnessio
  orgIdentifier: default
  tags: {}
  variables:
    - name: AWS_REGION
      type: String
      value: ap-south-1
    - name: ECR_REPO_URI
      type: String
      value: 680871073643.dkr.ecr.ap-south-1.amazonaws.com/nginx
  properties:
    ci:
      codebase:
        connectorRef: GitHub
        repoName: harness
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: Clone and Push NGINX to ECR
        identifier: push_nginx
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Show repo contents
                  identifier: show_repo
                  spec:
                    shell: Sh
                    command: |
                      echo "=== working dir ==="
                      pwd
                      echo "=== files ==="
                      ls -la
                      echo "=== Dockerfile ==="
                      [ -f Dockerfile ] && cat Dockerfile || echo "Dockerfile NOT FOUND"
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: aws_connector
                    region: ap-south-1
                    account: "680871073643"
                    imageName: nginx
                    tags:
                      - latest
          delegateSelectors:
            - docker5-delegate
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: Deploy NGINX to EC2
        identifier: deploy_nginx_ec2
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: Deploy Container from ECR
                  identifier: deploy_container
                  type: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: false
                    source:
                      type: Inline
                      spec:
                        script: |
                          # 🔧 Ensure Docker and AWS CLI are in PATH
                          export PATH=$PATH:/usr/local/bin:/usr/bin:/bin

                          echo "🔍 Checking tool availability..."
                          echo "PATH: $PATH"
                          which aws || { echo '❌ AWS CLI not found'; exit 1; }
                          which docker || { echo '❌ Docker not found'; exit 1; }

                          echo "🔐 Logging into ECR..."
                          aws ecr get-login-password --region ap-south-1 \
                          | docker login --username AWS --password-stdin 680871073643.dkr.ecr.ap-south-1.amazonaws.com

                          echo "📦 Pulling latest NGINX image..."
                          docker pull 680871073643.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest

                          echo "🧹 Cleaning up old container..."
                          docker stop nginx || true
                          docker rm nginx || true

                          echo "🚀 Running latest NGINX..."
                          docker run -d --name nginx -p 80:80 680871073643.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest
              - step:
                  name: Health Check
                  identifier: health_check
                  type: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "🩺 Checking if NGINX is up..."
                          sleep 5
                          curl --fail http://localhost || exit 1
          delegateSelectors:
            - ec2-delegate
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - docker5-delegate
