pipeline:
  name: Build and Push NGINX from Git Repo
  identifier: Build_adithya10_12ramesh_Harness_io_1751003503138
  projectIdentifier: Harnessio
  orgIdentifier: default
  tags: {}
  variables:
    - name: AWS_REGION
      type: String
      value: ap-south-1
    - name: ECR_REPO_URI
      type: String
      value: 680871073643.dkr.ecr.ap-south-1.amazonaws.com/nginx
  properties:
    ci:
      codebase:
        connectorRef: GitHub
        repoName: harness
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: Clone and Push NGINX to ECR
        identifier: push_nginx
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Show repo contents
                  identifier: show_repo
                  spec:
                    shell: Sh
                    command: |
                      echo "=== working dir ==="
                      pwd
                      echo "=== files ==="
                      ls -la
                      echo "=== Dockerfile ==="
                      [ -f Dockerfile ] && cat Dockerfile || echo "Dockerfile NOT FOUND"
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: aws_connector
                    region: ap-south-1
                    account: "680871073643"
                    imageName: nginx
                    tags:
                      - latest
          delegateSelectors:
            - docker5-delegate
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: Deploy to EC2
        identifier: deploy_to_ec2
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: Deploy Container
                  identifier: deploy_container
                  type: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: false
                    executionTarget:
                      host: 65.0.173.1
                      connectorRef: ssh-ec2-key3
                      workingDirectory: /home/ubuntu
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "🔐 Logging in to ECR..."
                          aws ecr get-login-password --region ap-south-1 \
                          | docker login --username AWS --password-stdin 680871073643.dkr.ecr.ap-south-1.amazonaws.com

                          echo "📦 Pulling image from ECR..."
                          docker pull 680871073643.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest

                          echo "🛑 Stopping existing container if any..."
                          docker stop nginx || true
                          docker rm nginx || true

                          echo "🚀 Running new container..."
                          docker run -d --name nginx -p 80:80 680871073643.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest
              - step:
                  name: Health Check
                  identifier: health_check
                  type: ShellScript
                  spec:
                    shell: Bash
                    onDelegate: false
                    executionTarget:
                      host: 65.0.173.1
                      connectorRef: ssh_key_connector
                      workingDirectory: /home/ec2-user
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "⏱ Waiting for container to start..."
                          sleep 10
                          echo "🔍 Checking NGINX availability..."
                          curl --fail http://localhost || exit 1
